Repository Hakamony/source, pull requests merged in 2024-08, with the labels that each got.

#27 Feature setup pages
  .prettierrc
  README.md
  package-lock.json
  package.json
  src/app/SelectEvent/page.jsx
  src/app/Summary/page.jsx
  src/app/page.jsx
  src/styles/globals.css
  tailwind.config.js
Labels: setup

#30 Setup selectevent page draft
  .eslintrc.json
  src/app/SelectEvent/page.jsx
  src/app/layout.jsx
  src/components/events/EventsNav.jsx
  src/styles/globals.css
Labels: page

#31 Feature local storage
  README.md
  src/app/page.jsx
  src/lib/storage/eventStorage.js
  src/lib/storage/matchStorage.js
  src/lib/storage/pastEventStorage.js
  src/lib/storage/playerStorage.js
  src/lib/storage/storageHelper.js
  src/lib/storage/teamStorage.js
Labels: function, feature

#32 Feature upload players page
  .eslintrc.json
  src/app/UploadPlayers/page.jsx
  src/app/layout.jsx
  src/components/events/AddPlayer.jsx
  src/components/events/EventsNav.jsx
  src/components/events/PlayersList.jsx
  src/components/events/UploadFile.jsx
  src/styles/globals.css
  tailwind.config.js
Labels: page

#33 Merge the Algorithems
  README.md
  src/lib/Algorithems/generateEvents.js
  src/lib/Algorithems/generateMatches.js
  src/lib/Algorithems/generateTeams.js
  src/lib/funct.js
Labels: function, feature

#35 Add tailwind merge package for dynamic styling
  package-lock.json
  package.json
Labels: feature, setup

#36 Fix UI styling loading issues
  src/app/page.jsx
  src/components/layout/ButtonNav.jsx
Labels: bug, page

#37 Fix steps nav UI stlying issues
  src/components/events/EventsNav.jsx
Labels: bug, page

#38 Feature game setting page
  src/app/GameSettings/page.jsx
  src/app/ScoreCounter/page.jsx
  src/app/Summary/page.jsx
  src/components/input/Counter.jsx
Labels: page, feature

#40 Feature-MergeAlgorithem+storage
  src/lib/Algorithems/generateMatches.js
  src/lib/Algorithems/generateTeams.js
  src/lib/Algorithems/tempCodeRunnerFile.js
  src/lib/storage/eventStorage.js
  src/lib/storage/matchStorage.js
  src/lib/storage/playerStorage.js
  src/lib/storage/teamStorage.js
Labels: function, feature

#42 Feature summary page
  src/app/Summary/page.jsx
Labels: page, feature
