Repository Hakamony/source, pull requests merged in 2024-09, with the labels that each got.

#45 Add page functionality and fix form UI
  src/app/GameSettings/page.jsx
  src/components/input/Counter.jsx
Labels: page, feature

#46 Add functions
  src/app/GameSettings/page.jsx
  src/app/UploadPlayers/page.jsx
  src/lib/Algorithems/generateMatches.js
Labels: function, feature

#47 Feature summary page
  .eslintrc.json
  src/app/Summary/page.jsx
  src/components/StorageButton.jsx
  src/components/events/PlayersList.jsx
  src/components/events/UploadFile.jsx
  src/lib/Algorithems/generateEvents.js
  src/lib/Algorithems/generateMatches.js
  src/lib/Algorithems/generateTeams.js
  src/lib/Algorithems/tempCodeRunnerFile.js
  src/lib/storage/matchStorage.js
  src/lib/storage/storageHelper.js
Labels: page, function, feature

#48 Feature event dashboard page
  src/app/EventDashboard/page.jsx
  src/components/events/MatchPopUp.jsx
  src/components/layout/Menu.jsx
Labels: page, function

#49 exportPlayers button
  src/app/UploadPlayers/page.jsx
  src/components/input/ExportPlayersButton.jsx
Labels: feature

#50 getNextMatch
  src/lib/storage/matchStorage.js
Labels: feature

#51 Feature summary page
  src/app/Summary/page.jsx
  src/components/events/EditMatches.jsx
  src/components/events/EditPlayers.jsx
  src/components/events/TeamsList.jsx
  src/lib/funct.js
Labels: page, feature

#53 Fix build process issue
  src/app/Summary/page.jsx
  src/components/events/EditMatches.jsx
  src/components/events/EditPlayers.jsx
  src/components/events/EventsNav.jsx
Labels: bug

#54 Fix UI bugs in all pages
  src/app/GameSettings/page.jsx
  src/app/Summary/page.jsx
  src/app/UploadPlayers/page.jsx
  src/app/layout.jsx
  src/app/page.jsx
  src/components/events/AddPlayer.jsx
  src/components/events/EditMatches.jsx
  src/components/events/EditPlayers.jsx
  src/components/events/PlayersList.jsx
  src/components/selectEvent/SelectEventsForm.jsx
Labels: bug

#55 Fix color proplems
  src/app/Summary/page.jsx
  src/app/UploadPlayers/page.jsx
  src/app/page.jsx
  src/components/events/EndEventPopUp.jsx
  src/components/events/EventsNav.jsx
  src/components/layout/ButtonNav.jsx
Labels: bug

#56 updated getNextMatch + players length added to event
  src/lib/storage/matchStorage.js
  src/lib/storage/playerStorage.js
Labels: function, feature

#57 Fix teams generation bug
  src/app/EventDashboard/page.jsx
  src/app/Summary/page.jsx
  src/components/StorageButton.jsx
  src/lib/Algorithems/generateMatches.js
  src/lib/storage/matchStorage.js
Labels: bug

#58 Hakamony version 1.0.0
  .eslintrc.json
  .prettierrc
  README.md
  package-lock.json
  package.json
  public/assets/hakamDraft.png
  src/app/EventDashboard/page.jsx
  src/app/GameSettings/page.jsx
  src/app/ScoreCounter/page.jsx
  src/app/SelectEvent/page.jsx
  src/app/Summary/page.jsx
  src/app/Summery/page.jsx
  src/app/UploadPlayers/page.jsx
  src/app/layout.jsx
  src/app/page.jsx
  src/components/StorageButton.jsx
  src/components/events/AddPlayer.jsx
  src/components/events/EditMatches.jsx
  src/components/events/EditPlayers.jsx
  src/components/events/EndEventPopUp.jsx
  src/components/events/EventsNav.jsx
  src/components/events/FieldCard.jsx
  src/components/events/MatchPopUp.jsx
  src/components/events/PlayersList.jsx
  src/components/events/PlayersPopUp.jsx
  src/components/events/TeamsList.jsx
  src/components/events/UploadFile.jsx
  src/components/input/Counter.jsx
  src/components/input/ExportPlayersButton.jsx
  src/components/layout/ButtonNav.jsx
  src/components/layout/Menu.jsx
  src/components/selectEvent/SelectEventsForm.jsx
  src/lib/Algorithems/generateEvents.js
  src/lib/Algorithems/generateMatches.js
  src/lib/Algorithems/generateTeams.js
  src/lib/funct.js
  src/lib/storage/eventStorage.js
  src/lib/storage/matchStorage.js
  src/lib/storage/pastEventStorage.js
  src/lib/storage/playerStorage.js
  src/lib/storage/storageHelper.js
  src/lib/storage/teamStorage.js
  src/styles/globals.css
  tailwind.config.js
Labels: setup

#59 generate matches bug
  src/lib/Algorithems/generateMatches.js
Labels: bug

#64 update team rating and players number in teams object
  src/lib/storage/teamStorage.js
Labels: bug

#65 Fix UI issues
  public/assets/field.avif
  public/assets/field.jpg
  public/assets/texture-full-screen.png
  src/app/EventDashboard/page.jsx
  src/app/GameSettings/page.jsx
  src/app/SelectEvent/page.jsx
  src/app/Summary/page.jsx
  src/app/UploadPlayers/page.jsx
  src/app/layout.jsx
  src/app/page.jsx
  src/components/events/AddPlayer.jsx
  src/components/events/EditMatches.jsx
  src/components/events/EditPlayers.jsx
  src/components/events/EndEventPopUp.jsx
  src/components/events/EventsNav.jsx
  src/components/events/FieldCard.jsx
  src/components/events/PlayersList.jsx
  src/components/events/PlayersPopUp.jsx
  src/components/events/TeamsList.jsx
  src/components/events/UploadFile.jsx
  src/components/input/ExportPlayersButton.jsx
  src/components/layout/ButtonNav.jsx
  src/components/selectEvent/SelectEventsForm.jsx
  src/lib/Algorithems/generateMatches.js
  src/styles/globals.css
  tailwind.config.js
Labels: bug, page, feature

#66 Dev
  public/assets/field.avif
  public/assets/field.jpg
  public/assets/texture-full-screen.png
  src/app/EventDashboard/page.jsx
  src/app/GameSettings/page.jsx
  src/app/SelectEvent/page.jsx
  src/app/Summary/page.jsx
  src/app/UploadPlayers/page.jsx
  src/app/layout.jsx
  src/app/page.jsx
  src/components/events/AddPlayer.jsx
  src/components/events/EditMatches.jsx
  src/components/events/EditPlayers.jsx
  src/components/events/EndEventPopUp.jsx
  src/components/events/EventsNav.jsx
  src/components/events/FieldCard.jsx
  src/components/events/PlayersList.jsx
  src/components/events/PlayersPopUp.jsx
  src/components/events/TeamsList.jsx
  src/components/events/UploadFile.jsx
  src/components/input/ExportPlayersButton.jsx
  src/components/layout/ButtonNav.jsx
  src/components/selectEvent/SelectEventsForm.jsx
  src/lib/Algorithems/generateMatches.js
  src/lib/storage/teamStorage.js
  src/styles/globals.css
  tailwind.config.js
Labels: feature

#67 Fix UI issues
  src/app/GameSettings/page.jsx
  src/app/Summary/page.jsx
  src/app/layout.jsx
  src/app/page.jsx
  src/components/events/AddPlayer.jsx
  src/components/events/PlayersList.jsx
  src/styles/globals.css
Labels: bug, function, feature

#68 Fix end game function issues
  src/app/EventDashboard/page.jsx
  src/components/events/FieldCard.jsx
  src/lib/Algorithems/generateMatches.js
  src/lib/Algorithems/generateTeams.js
Labels: bug, function

#69 Fix UI issues
  public/assets/clipboard.png
  public/assets/team-icon.jpg
  src/app/EventDashboard/page.jsx
  src/app/GameSettings/page.jsx
  src/app/Summary/page.jsx
  src/components/events/AddPlayer.jsx
  src/components/events/FieldCard.jsx
  src/components/events/PlayersList.jsx
  src/lib/Algorithems/generateMatches.js
  src/styles/globals.css
Labels: bug, feature

#72 Fix UI issues
  src/app/EventDashboard/page.jsx
  src/app/GameSettings/page.jsx
  src/components/events/FieldCard.jsx
  src/components/events/HistoryCard.jsx
  src/components/events/MatchPopUp.jsx
  src/components/selectEvent/SelectEventsForm.jsx
  src/lib/Algorithems/generateMatches.js
  src/lib/storage/matchStorage.js
  src/styles/globals.css
Labels: function, feature

#73 Add score ccounter function
  src/components/events/FieldCard.jsx
  src/components/events/MatchPopUp.jsx
Labels: function, feature
